apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-db-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-db-svc
  template:
    metadata:
      labels:
        app: health-db-svc
    spec:
      containers:
        - name: health-db-svc
          image: eugenebalykov/health-db-svc:latest
          ports:
            - containerPort: 5005
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: health-db-svc-secret
                  key: database-url

---

apiVersion: v1
kind: Service
metadata:
  name: health-db-svc
spec:
  type: ClusterIP
  selector:
    app: health-db-svc
  ports:
    - name: grpc
      port: 5005
      targetPort: 5005
      protocol: TCP


---

apiVersion: v1
kind: Secret
metadata:
  name: health-db-svc-secret
type: Opaque
data:
  # postgres://postgres:postgres-pass@postgres-access:5432/health_database?sslmode=disable
  database-url: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlcy1wYXNzQHBvc3RncmVzLWFjY2Vzczo1NDMyL2hlYWx0aF9kYXRhYmFzZT9zc2xtb2RlPWRpc2FibGU=